#!/bin/bash

export ENV=
export FACEBOOK_CLIENT_ID=
export FACEBOOK_CLIENT_SECRET=
export FACEBOOK_CALLBACK=
export TWITTER_CLIENT_ID=
export TWITTER_CLIENT_SECRET=
export TWITTER_CALLBACK=
export MONGOLAB_URI=
export REDISTOGO_URL=
export SESSION_KEY=
export SESSION_SECRET=